import { useEffect, useState } from "react";
import { Check, MessageSquare, Phone, RefreshCw, Truck } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";

type OrderRow = { id: string; order_number: string; business_name: string; phone: string; status: string; representative_name: string | null; representative_phone: string | null; internal_notes: string | null; customer_note: string | null; total: number };
const statuses = ["معلق", "تم التأكيد", "قيد التجهيز", "في الشحن", "تم التسليم", "ملغي"];

export default function OrderOperations() {
  const [orders, setOrders] = useState<OrderRow[]>([]); const [selected, setSelected] = useState<OrderRow | null>(null); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ status: "معلق", representative_name: "", representative_phone: "", note: "", customer_note: "" });
  const load = async () => { const { data, error } = await supabase.from("orders").select("id,order_number,business_name,phone,status,representative_name,representative_phone,internal_notes,customer_note,total").order("created_at", { ascending: false }).limit(50); if (error) return toast.error("تعذر تحميل الطلبات — تأكد من migration"); setOrders((data || []) as OrderRow[]); };
  useEffect(() => { void load(); }, []);
  const pick = (order: OrderRow) => { setSelected(order); setForm({ status: order.status || "معلق", representative_name: order.representative_name || "", representative_phone: order.representative_phone || "", note: "", customer_note: order.customer_note || "" }); };
  const save = async () => { if (!selected) return; setBusy(true); const { error: oe } = await supabase.from("orders").update({ status: form.status, representative_name: form.representative_name || null, representative_phone: form.representative_phone || null, customer_note: form.customer_note || null, internal_notes: form.note || selected.internal_notes }).eq("id", selected.id); if (!oe) { const { error: ee } = await supabase.from("order_status_events").insert({ order_id: selected.id, status: form.status, note: form.note || form.customer_note || null, visible_to_customer: true }); if (ee) toast.error(ee.message); } setBusy(false); if (oe) return toast.error(oe.message || "تعذر حفظ الطلب"); toast.success("تم تحديث الطلب وإظهار البيانات للعميل"); setSelected(null); await load(); };
  return <div className="page-stack"><div className="page-intro"><div><div className="eyebrow">التشغيل والشحن</div><h2>إدارة الطلبات والتوصيل</h2><p>حدّث الحالة، عيّن المندوب، وأضف ملاحظة تظهر للعميل في صفحة التتبع.</p></div><button className="secondary-button" onClick={() => void load()}><RefreshCw size={15} /> تحديث</button></div><div className="orders-operation-layout"><div className="panel"><div className="panel-header"><div><span className="panel-kicker">آخر الطلبات</span><h3>قائمة الطلبات</h3></div><Truck size={20} /></div><div className="orders-ops-list">{orders.length === 0 ? <div className="empty-state">لا توجد طلبات أو لم يتم تطبيق مخطط الطلبات بعد.</div> : orders.map((order) => <button className={`order-ops-row ${selected?.id === order.id ? "selected" : ""}`} key={order.id} onClick={() => pick(order)}><div><b>{order.order_number}</b><span>{order.business_name} • {order.phone}</span></div><strong>{order.status}</strong><small>{Number(order.total || 0).toFixed(2)} ج.م</small></button>)}</div></div>{selected && <div className="panel order-editor"><div className="panel-header"><div><span className="panel-kicker">{selected.order_number}</span><h3>تحديث بيانات الشحن</h3></div><button className="icon-button" onClick={() => setSelected(null)}>×</button></div><label>حالة الطلب<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><div className="form-grid-2"><label>اسم المندوب<input value={form.representative_name} onChange={(e) => setForm({ ...form, representative_name: e.target.value })} placeholder="مثال: أحمد حسن" /></label><label>هاتف المندوب<input value={form.representative_phone} onChange={(e) => setForm({ ...form, representative_phone: e.target.value })} placeholder="01xxxxxxxxx" /></label></div><label>ملاحظة للعميل<textarea value={form.customer_note} onChange={(e) => setForm({ ...form, customer_note: e.target.value })} placeholder="مثال: الطلب خرج من المخزن وسيصل اليوم" /></label><label>ملاحظة داخلية<textarea value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} placeholder="ملاحظة لفريق التشغيل" /></label><button className="primary-button full-width" disabled={busy} onClick={() => void save()}><Check size={15} /> حفظ وإظهار التحديث</button><div className="representative-preview"><Phone size={15} /><span>{form.representative_name || "لم يتم تعيين مندوب"}</span>{form.representative_phone && <a href={`tel:${form.representative_phone}`}>{form.representative_phone}</a>}<MessageSquare size={15} /></div></div>}</div></div>;
}
